project: astra-self-attn-multi-task-no-recomp
entity: lmse-university-of-toronto

command:
  - ${env}
  - python
  - ${program} # This will be the script path
  - --base_config
  - "configs/hpo/self-attn/multi-task-no-recomp/cpi_self_attn_model_config_base.yaml" # Relative to PROJECT_ROOT
  - ${args}

program: "../../../scripts/run_experiment/run_sweep_self_attn.py"
method: bayes
metric:
  name: valid_loss_epoch
  goal: minimize

parameters:
  lr:
    distribution: log_uniform_values
    min: 1.0e-5
    max: 1.0e-2
  batch_size:
    values: [32, 64, 128]

  n_heads:
    values: [1, 2, 4, 8, 16, 32]
  d_k:
    values: [32, 64, 128, 256, 512]
  d_v:
    values: [32, 64, 128, 256, 512]
  d_ff:
    values: [32, 64, 128, 256, 512, 1024]

  w_kcat_logit:
    distribution: uniform
    min: -2.0
    max: 2.0
  w_km_logit:
    distribution: uniform
    min: -2.0
    max: 2.0
  w_ki_logit:
    distribution: uniform
    min: -2.0
    max: 2.0