[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "astra"
version = "0.1.0"
description = "Machine learning project for predicting enzyme kinetic parameters."
readme = "design.md"
authors = [
    { 
        name = "Maxim Kirby", 
        email = "maxim.kirby@mail.utoronto.ca" 
    }
]
requires-python = ">=3.8"
dependencies = []